server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#    等待创建服务器的mysql
#    driverClassName: com.mysql.jdbc.Driver
